# Generated by Django 3.1.2 on 2020-10-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_maincontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincontact',
            name='service1',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
