# Generated by Django 3.1.2 on 2020-10-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201031_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincontact',
            name='service10',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='maincontact',
            name='service11',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='maincontact',
            name='service12',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='maincontact',
            name='service2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='maincontact',
            name='service3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='maincontact',
            name='service4',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='maincontact',
            name='service5',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='maincontact',
            name='service6',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='maincontact',
            name='service7',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='maincontact',
            name='service8',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='maincontact',
            name='service9',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='maincontact',
            name='attachment',
            field=models.FileField(null=True, upload_to='static/contactform/attachments'),
        ),
        migrations.AlterField(
            model_name='maincontact',
            name='company',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='maincontact',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='maincontact',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
