# Generated by Django 3.1.2 on 2020-10-31 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201031_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincontact',
            name='service10',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='maincontact',
            name='service11',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='maincontact',
            name='service12',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='maincontact',
            name='service2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='maincontact',
            name='service3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='maincontact',
            name='service4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='maincontact',
            name='service5',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='maincontact',
            name='service6',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='maincontact',
            name='service7',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='maincontact',
            name='service8',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='maincontact',
            name='service9',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
