# Generated by Django 3.1.2 on 2020-11-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_infographics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
                ('project', models.CharField(max_length=200)),
                ('job_location', models.CharField(max_length=200)),
                ('work_timing', models.CharField(max_length=200)),
                ('weekly_off', models.CharField(max_length=200)),
                ('education', models.CharField(max_length=200)),
                ('emp_type', models.CharField(max_length=200)),
                ('salary', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=200)),
                ('skills', models.CharField(max_length=200)),
                ('requirement', models.TextField()),
                ('interview_type', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('others', models.CharField(max_length=200)),
            ],
        ),
    ]
