# Generated by Django 3.1.2 on 2020-10-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='para1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='para2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='para3',
            field=models.TextField(default=''),
        ),
    ]
