# Generated by Django 3.1.2 on 2020-10-27 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201027_1731'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
