# Generated by Django 3.1.2 on 2020-10-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0003_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='static/resources/blog-images')),
                ('body', models.TextField()),
                ('head1', models.CharField(blank=True, max_length=200)),
                ('para1', models.TextField(blank=True)),
                ('image1', models.ImageField(blank=True, upload_to='static/resources/blog-images')),
                ('head2', models.CharField(blank=True, max_length=200)),
                ('para2', models.TextField(blank=True)),
                ('image2', models.ImageField(blank=True, upload_to='static/resources/blog-images')),
                ('head3', models.CharField(blank=True, max_length=200)),
                ('para3', models.TextField(blank=True)),
                ('image3', models.ImageField(blank=True, upload_to='static/resources/blog-images')),
                ('head4', models.CharField(blank=True, max_length=200)),
                ('para4', models.TextField(blank=True)),
                ('image4', models.ImageField(blank=True, upload_to='static/resources/blog-images')),
                ('head5', models.CharField(blank=True, max_length=200)),
                ('para5', models.TextField(blank=True)),
                ('image5', models.ImageField(blank=True, upload_to='static/resources/blog-images')),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
