# Generated by Django 3.1.2 on 2020-10-31 19:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='head1',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='head2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='head3',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='head4',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='head5',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='para1',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='para2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='para3',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='para4',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='para5',
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
